version: '3.8'

services:
  stt:
    build:
      context: ./stt
      dockerfile: Dockerfile
    environment:
      - STT_PATH_FILE=${STT_PATH_FILE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5001:5001"
    networks:
    - my-network
  
  client:
    build:
      context: ./client-streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
    - my-network

networks:
  my-network:
    driver: bridge